/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/layout'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardUtilitiesRouteImport } from './routes/dashboard/utilities'
import { Route as DashboardUnitsRouteImport } from './routes/dashboard/units'
import { Route as DashboardTodosRouteImport } from './routes/dashboard/todos'
import { Route as DashboardTenantsRouteImport } from './routes/dashboard/tenants'
import { Route as DashboardStaffRouteImport } from './routes/dashboard/staff'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as DashboardAdminLayoutRouteImport } from './routes/dashboard/admin/layout'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardUtilitiesRoute = DashboardUtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardUnitsRoute = DashboardUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardTodosRoute = DashboardTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardTenantsRoute = DashboardTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardAdminLayoutRoute = DashboardAdminLayoutRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminLayoutRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/units': typeof DashboardUnitsRoute
  '/dashboard/utilities': typeof DashboardUtilitiesRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/units': typeof DashboardUnitsRoute
  '/dashboard/utilities': typeof DashboardUtilitiesRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminLayoutRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/dashboard/todos': typeof DashboardTodosRoute
  '/dashboard/units': typeof DashboardUnitsRoute
  '/dashboard/utilities': typeof DashboardUtilitiesRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/auth/signup'
    | '/dashboard/payments'
    | '/dashboard/staff'
    | '/dashboard/tenants'
    | '/dashboard/todos'
    | '/dashboard/units'
    | '/dashboard/utilities'
    | '/auth/'
    | '/dashboard/'
    | '/profile'
    | '/dashboard/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signup'
    | '/dashboard/payments'
    | '/dashboard/staff'
    | '/dashboard/tenants'
    | '/dashboard/todos'
    | '/dashboard/units'
    | '/dashboard/utilities'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/dashboard/admin'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/auth/signup'
    | '/dashboard/payments'
    | '/dashboard/staff'
    | '/dashboard/tenants'
    | '/dashboard/todos'
    | '/dashboard/units'
    | '/dashboard/utilities'
    | '/auth/'
    | '/dashboard/'
    | '/profile/'
    | '/dashboard/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/utilities': {
      id: '/dashboard/utilities'
      path: '/utilities'
      fullPath: '/dashboard/utilities'
      preLoaderRoute: typeof DashboardUtilitiesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/units': {
      id: '/dashboard/units'
      path: '/units'
      fullPath: '/dashboard/units'
      preLoaderRoute: typeof DashboardUnitsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/todos': {
      id: '/dashboard/todos'
      path: '/todos'
      fullPath: '/dashboard/todos'
      preLoaderRoute: typeof DashboardTodosRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/tenants': {
      id: '/dashboard/tenants'
      path: '/tenants'
      fullPath: '/dashboard/tenants'
      preLoaderRoute: typeof DashboardTenantsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface DashboardAdminLayoutRouteChildren {
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminLayoutRouteChildren: DashboardAdminLayoutRouteChildren = {
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminLayoutRouteWithChildren =
  DashboardAdminLayoutRoute._addFileChildren(DashboardAdminLayoutRouteChildren)

interface DashboardLayoutRouteChildren {
  DashboardAdminLayoutRoute: typeof DashboardAdminLayoutRouteWithChildren
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardStaffRoute: typeof DashboardStaffRoute
  DashboardTenantsRoute: typeof DashboardTenantsRoute
  DashboardTodosRoute: typeof DashboardTodosRoute
  DashboardUnitsRoute: typeof DashboardUnitsRoute
  DashboardUtilitiesRoute: typeof DashboardUtilitiesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardAdminLayoutRoute: DashboardAdminLayoutRouteWithChildren,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardStaffRoute: DashboardStaffRoute,
  DashboardTenantsRoute: DashboardTenantsRoute,
  DashboardTodosRoute: DashboardTodosRoute,
  DashboardUnitsRoute: DashboardUnitsRoute,
  DashboardUtilitiesRoute: DashboardUtilitiesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
